kernel/generic: fix build failure on missing uhci symbol
linux-3.6.8/drivers/usb/host/pci-quirks.c:471: undefined reference to
`uhci_check_and_reset_hc'

Signed-off-by: Florian Fainelli <florian@openwrt.org>

git-svn-id: svn://svn.openwrt.org/openwrt/trunk@34599 3c298f89-4303-0410-b956-a3cf2f4a3e73